#
# Copyright 2018 CompuLab
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += ucm-imx8m-mini.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += ddr/lpddr4_timing_1g.o ddr/lpddr4_timing_2g.o
endif
